diff supabase/config.toml qtwmykpyhcvfavjgncty
--- supabase/config.toml
+++ qtwmykpyhcvfavjgncty
@@ -2,7 +2,7 @@
 
 [api]
 enabled = true
-schemas = ["public", "graphql_public"]
+schemas = ["public", "graphql_public"]
 extra_search_path = ["public", "extensions"]
 max_rows = 1000
 port = 54321
@@ -54,8 +54,8 @@
 
 [auth]
 enabled = true
-site_url = "http://127.0.0.1:3000"
-additional_redirect_urls = ["https://127.0.0.1:3000"]
+site_url = "http://localhost:3000"
+additional_redirect_urls = []
 jwt_expiry = 3600
 enable_refresh_token_rotation = true
 refresh_token_reuse_interval = 10
@@ -79,8 +79,8 @@
 [auth.mfa]
 max_enrolled_factors = 10
 [auth.mfa.totp]
-enroll_enabled = false
-verify_enabled = false
+enroll_enabled = true
+verify_enabled = true
 [auth.mfa.phone]
 enroll_enabled = false
 verify_enabled = false
@@ -96,11 +96,11 @@
 [auth.email]
 enable_signup = true
 double_confirm_changes = true
-enable_confirmations = false
+enable_confirmations = true
 secure_password_change = false
-max_frequency = "1s"
-otp_length = 6
-otp_expiry = 3600
+max_frequency = "1m0s"
+otp_length = 6
+otp_expiry = 86400
 [auth.email.template]
 [auth.sms]
 enable_signup = false
@@ -141,7 +141,7 @@
 skip_nonce_check = false
 [auth.web3]
 [auth.web3.solana]
-enabled = false
+enabled = true
 [auth.third_party]
 [auth.third_party.firebase]
 enabled = false